'use client'

/**
 * SmartInsight — AI-generated supply chain risk summary
 * ─────────────────────────────────────────────────────────────
 * Displays a 1-sentence risk insight generated by Claude, with:
 *   • Colour-coded risk badge (Critical → Low)
 *   • Typewriter reveal animation on the sentence
 *   • Shimmer skeleton while fetching
 *   • Inline retry on error
 *   • Cache indicator (⚡ cached vs ◎ live)
 *   • Regenerate button
 */

import { useEffect, useState, useRef, useCallback } from 'react'
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion'
import { useSmartInsight } from '@/hooks/useSmartInsight'
import { Shimmer } from '@/components/ui/skeletons'
import type { Company, SupplyChainLayer } from '@/types/supply-chain'
import type { InsightResponse } from '@/app/api/insight/route'

// ─────────────────────────────────────────────────────────────
// RISK CONFIG — visual treatment per level
// ─────────────────────────────────────────────────────────────

type RiskLevel = InsightResponse['riskLevel']

interface RiskConfig {
  label:       string
  badgeBg:     string
  badgeText:   string
  badgeBorder: string
  barColor:    string
  dotColor:    string
  glowColor:   string
  icon:        string
}

const RISK_CONFIG: Record<RiskLevel, RiskConfig> = {
  critical: {
    label:       'CRITICAL RISK',
    badgeBg:     'bg-red-500/12',
    badgeText:   'text-red-400',
    badgeBorder: 'border-red-500/35',
    barColor:    'bg-red-500',
    dotColor:    'bg-red-500',
    glowColor:   'rgba(239,68,68,0.12)',
    icon:        '⚠',
  },
  high: {
    label:       'HIGH RISK',
    badgeBg:     'bg-orange-500/12',
    badgeText:   'text-orange-400',
    badgeBorder: 'border-orange-500/35',
    barColor:    'bg-orange-500',
    dotColor:    'bg-orange-500',
    glowColor:   'rgba(249,115,22,0.12)',
    icon:        '↑',
  },
  moderate: {
    label:       'MODERATE RISK',
    badgeBg:     'bg-amber-500/12',
    badgeText:   'text-amber-400',
    badgeBorder: 'border-amber-500/35',
    barColor:    'bg-amber-500',
    dotColor:    'bg-amber-500',
    glowColor:   'rgba(245,158,11,0.12)',
    icon:        '◈',
  },
  low: {
    label:       'LOW RISK',
    badgeBg:     'bg-emerald-500/12',
    badgeText:   'text-emerald-400',
    badgeBorder: 'border-emerald-500/35',
    barColor:    'bg-emerald-500',
    dotColor:    'bg-emerald-500',
    glowColor:   'rgba(34,197,94,0.10)',
    icon:        '✓',
  },
  unknown: {
    label:       'ANALYSING',
    badgeBg:     'bg-zinc-700/30',
    badgeText:   'text-zinc-500',
    badgeBorder: 'border-zinc-700/40',
    barColor:    'bg-zinc-600',
    dotColor:    'bg-zinc-600',
    glowColor:   'rgba(0,0,0,0)',
    icon:        '○',
  },
}

// ─────────────────────────────────────────────────────────────
// TYPEWRITER — reveals insight text character by character
// ─────────────────────────────────────────────────────────────

interface TypewriterProps {
  text:     string
  speed?:   number    // ms per character
  onDone?:  () => void
}

function Typewriter({ text, speed = 18, onDone }: TypewriterProps): React.ReactElement {
  const reduced              = useReducedMotion()
  const [displayed, setDisplayed] = useState('')
  const indexRef             = useRef(0)
  const timerRef             = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    // Reset on new text
    setDisplayed('')
    indexRef.current = 0

    if (reduced) {
      // Skip animation — show all at once
      setDisplayed(text)
      onDone?.()
      return
    }

    function tick(): void {
      if (indexRef.current >= text.length) {
        onDone?.()
        return
      }
      setDisplayed(text.slice(0, indexRef.current + 1))
      indexRef.current += 1
      timerRef.current = setTimeout(tick, speed)
    }

    timerRef.current = setTimeout(tick, speed)
    return () => { if (timerRef.current) clearTimeout(timerRef.current) }
  }, [text, speed, reduced, onDone])

  return (
    <span aria-label={text} aria-live="polite">
      {displayed}
      {displayed.length < text.length && (
        <motion.span
          animate={{ opacity: [1, 0] }}
          transition={{ duration: 0.5, repeat: Infinity, repeatType: 'reverse' }}
          className="inline-block w-px h-3.5 bg-current ml-0.5 align-middle"
          aria-hidden="true"
        />
      )}
    </span>
  )
}

// ─────────────────────────────────────────────────────────────
// RISK METER — 4-segment horizontal bar
// ─────────────────────────────────────────────────────────────

function RiskMeter({ level }: { level: RiskLevel }): React.ReactElement {
  const segments: RiskLevel[] = ['low', 'moderate', 'high', 'critical']
  const activeIndex = segments.indexOf(level)

  return (
    <div className="flex items-center gap-1" aria-label={`Risk meter: ${level}`}>
      {segments.map((seg, i) => {
        const cfg    = RISK_CONFIG[seg]
        const filled = activeIndex !== -1 && i <= activeIndex

        return (
          <motion.div
            key={seg}
            initial={{ scaleX: 0 }}
            animate={{ scaleX: 1 }}
            transition={{ delay: i * 0.06, duration: 0.3, ease: 'easeOut' }}
            style={{ originX: 0 }}
            className={[
              'h-1 rounded-full flex-1',
              filled ? cfg.barColor : 'bg-[#242B36]',
            ].join(' ')}
          />
        )
      })}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SKELETON STATE — while insight is generating
// ─────────────────────────────────────────────────────────────

function InsightSkeleton(): React.ReactElement {
  return (
    <div className="flex flex-col gap-3">
      {/* Header row */}
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Shimmer className="h-5 w-24" rounded="rounded-md" />
          <Shimmer className="h-3 w-3" rounded="rounded-full" />
        </div>
        <Shimmer className="h-4 w-16" rounded="rounded-full" />
      </div>

      {/* Risk meter */}
      <div className="flex gap-1">
        {[0, 1, 2, 3].map((i) => (
          <Shimmer key={i} className="h-1 flex-1" rounded="rounded-full" />
        ))}
      </div>

      {/* Insight text: 2 lines */}
      <div className="flex flex-col gap-1.5 mt-0.5">
        <Shimmer className="h-3.5 w-full" />
        <Shimmer className="h-3.5 w-[72%]" />
      </div>

      {/* Footer */}
      <div className="flex items-center gap-2 mt-1">
        <Shimmer className="h-3 w-8" rounded="rounded-full" />
        <Shimmer className="h-3 w-20" />
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// MAIN EXPORT: SmartInsight
// ─────────────────────────────────────────────────────────────

interface SmartInsightProps {
  company: Company
  layer:   Pick<SupplyChainLayer, 'id' | 'title'>
}

export function SmartInsight({ company, layer }: SmartInsightProps): React.ReactElement {
  const { insight, riskLevel, status, error, cached, refetch } = useSmartInsight(company, layer)
  const [typewriterDone, setTypewriterDone] = useState(false)
  const cfg = RISK_CONFIG[riskLevel]

  // Reset typewriter state when a new insight arrives
  useEffect(() => {
    if (status === 'success') setTypewriterDone(false)
  }, [insight, status])

  const handleRegenerateClick = useCallback((): void => {
    setTypewriterDone(false)
    refetch()
  }, [refetch])

  return (
    <section
      aria-label="AI Supply Chain Risk Insight"
      className="px-5 py-4 border-b border-[#242B36]"
    >
      {/* ── Section label ── */}
      <div className="flex items-center gap-2 mb-3">
        <p className="text-[9px] font-mono text-zinc-600 uppercase tracking-widest">
          GS Smart Insight
        </p>
        <span
          className="text-[9px] font-mono px-1.5 py-0.5 rounded-sm bg-amber-500/10 text-amber-500/80 border border-amber-500/20"
          aria-label="Powered by Claude AI"
        >
          AI
        </span>
      </div>

      {/* ── Content area ── */}
      <AnimatePresence mode="wait">

        {/* LOADING */}
        {(status === 'idle' || status === 'loading') && (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, transition: { duration: 0.1 } }}
            transition={{ duration: 0.15 }}
          >
            <InsightSkeleton />
          </motion.div>
        )}

        {/* ERROR */}
        {status === 'error' && (
          <motion.div
            key="error"
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="flex items-start gap-3 p-3 rounded-xl border border-red-500/20 bg-red-500/5"
          >
            <span className="text-red-400 text-sm mt-0.5 flex-shrink-0" aria-hidden="true">⚠</span>
            <div className="flex-1 min-w-0">
              <p className="text-[11px] font-mono text-red-400/80 leading-relaxed">
                {error ?? 'Insight generation failed.'}
              </p>
              <button
                onClick={handleRegenerateClick}
                className="
                  mt-2 text-[10px] font-mono text-red-400 hover:text-red-300
                  underline underline-offset-2 focus-visible:outline-none
                  focus-visible:ring-1 focus-visible:ring-red-500/50 rounded
                "
              >
                Retry
              </button>
            </div>
          </motion.div>
        )}

        {/* SUCCESS */}
        {status === 'success' && insight !== null && (
          <motion.div
            key={`insight-${insight.slice(0, 20)}`}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.28, ease: 'easeOut' }}
          >
            {/* ── Card shell with risk-level glow ── */}
            <div
              className={[
                'rounded-xl border p-4 transition-all duration-500',
                cfg.badgeBg,
                cfg.badgeBorder,
              ].join(' ')}
              style={{ boxShadow: `0 0 24px ${cfg.glowColor}, 0 0 48px ${cfg.glowColor}` }}
            >
              {/* Top row: badge + pulse dot + meter */}
              <div className="flex items-center justify-between gap-3 mb-2.5">
                <div className="flex items-center gap-2">
                  {/* Risk badge */}
                  <span
                    className={[
                      'text-[9px] font-mono font-semibold tracking-widest uppercase',
                      'px-2 py-1 rounded-md border',
                      cfg.badgeBg,
                      cfg.badgeText,
                      cfg.badgeBorder,
                    ].join(' ')}
                  >
                    {cfg.icon} {cfg.label}
                  </span>

                  {/* Animated pulse dot */}
                  {(riskLevel === 'critical' || riskLevel === 'high') && (
                    <motion.span
                      className={`w-1.5 h-1.5 rounded-full ${cfg.dotColor} flex-shrink-0`}
                      animate={{ scale: [1, 1.6, 1], opacity: [1, 0.4, 1] }}
                      transition={{ duration: 1.8, repeat: Infinity, ease: 'easeInOut' }}
                      aria-hidden="true"
                    />
                  )}
                </div>

                {/* Cache / source indicator */}
                <span className={`text-[9px] font-mono ${cfg.badgeText} opacity-60 flex-shrink-0`}>
                  {cached ? '⚡ cached' : '◎ live'}
                </span>
              </div>

              {/* Risk meter bar */}
              <div className="mb-3">
                <RiskMeter level={riskLevel} />
              </div>

              {/* ── Insight text with typewriter ── */}
              <p className={`text-sm font-mono leading-relaxed ${cfg.badgeText}`}>
                <Typewriter
                  text={insight}
                  speed={16}
                  onDone={() => setTypewriterDone(true)}
                />
              </p>

              {/* Footer: model credit + regenerate */}
              <AnimatePresence>
                {typewriterDone && (
                  <motion.div
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.2, delay: 0.1 }}
                    className="flex items-center justify-between mt-3 pt-2.5 border-t border-current/10"
                  >
                    <p className="text-[9px] font-mono opacity-40">
                      Claude · claude-sonnet-4-20250514 · GS Supply Chain Model
                    </p>
                    <button
                      onClick={handleRegenerateClick}
                      aria-label="Regenerate insight"
                      className={[
                        'text-[9px] font-mono opacity-50 hover:opacity-90',
                        'flex items-center gap-1 transition-opacity duration-150',
                        'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-current/50 rounded',
                        cfg.badgeText,
                      ].join(' ')}
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="10" height="10" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" strokeWidth="2.5"
                        strokeLinecap="round" strokeLinejoin="round"
                        aria-hidden="true"
                      >
                        <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8" />
                        <path d="M21 3v5h-5" />
                      </svg>
                      Regenerate
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        )}

      </AnimatePresence>
    </section>
  )
}
